"""Differential oracle for fundacad-geom's mesh export writers, generated by the Python sidecar.

The writers are compared byte for byte: each fixture BREP (shared with
tests/mesh_oracle) is tessellated coarsely, the arrays are stored as the
writers' input, and the Python writers' outputs are stored as blake2b-128
hashes, so no model file is committed. The export-grade mesh itself comes from
OCCT 7.9.3 here and 7.8.1 in Rust, so it is summarised, not hashed.

Run from anywhere with the sidecar's interpreter:
    sidecar/.venv/Scripts/python.exe crates/fundacad-geom/tests/export/gen.py
"""

import hashlib
import json
import os
import struct
import sys
import tempfile
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
ORACLE = os.path.normpath(os.path.join(HERE, "..", "mesh_oracle"))
SIDECAR = os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", "sidecar"))
sys.path.insert(0, SIDECAR)
os.chdir(SIDECAR)

import numpy as np  # noqa: E402
from OCP.BRep import BRep_Builder  # noqa: E402
from OCP.BRepTools import BRepTools  # noqa: E402
from OCP.TopoDS import TopoDS_Shape  # noqa: E402

import mesh_refine  # noqa: E402
import mesh_writers  # noqa: E402
import server  # noqa: E402
from shape_util import _wrap_topods  # noqa: E402
from tessellate import tessellate  # noqa: E402

FIXTURES = ["box", "box_minus_cylinder", "sphere", "two_solids"]
WRITER_TOL = 0.2


def read(name):
    topods = TopoDS_Shape()
    BRepTools.Read_s(topods, os.path.join(ORACLE, name + ".brep"), BRep_Builder())
    return _wrap_topods(topods)


def digest(data):
    return hashlib.blake2b(data, digest_size=16).hexdigest()


def file_digest(path):
    with open(path, "rb") as fh:
        return digest(fh.read())


def model_digest(path):
    with zipfile.ZipFile(path) as z:
        return {n: digest(z.read(n)) for n in z.namelist()}


def mesh_stats(pos, idx):
    P = np.asarray(pos, dtype=np.float64).reshape(-1, 3)
    T = np.asarray(idx, dtype=np.int64).reshape(-1, 3)
    a, b, c = P[T[:, 0]], P[T[:, 1]], P[T[:, 2]]
    area = float(np.linalg.norm(np.cross(b - a, c - a), axis=1).sum() / 2)
    volume = float(np.einsum("ij,ij->i", a, np.cross(b, c)).sum() / 6)
    return {"triangles": len(T), "volume": volume, "area": area}


def save_arrays(name, pos, idx):
    pos = np.asarray(pos, dtype=np.float64)
    idx = np.asarray(idx, dtype=np.uint32)
    with open(os.path.join(HERE, name + ".mesh"), "wb") as fh:
        fh.write(struct.pack("<II", len(pos) // 3, len(idx) // 3))
        fh.write(pos.tobytes())
        fh.write(idx.tobytes())


def capped(pos, idx, max_edge, budget):
    cpos, cidx = mesh_refine.cap_edge_length(pos, idx, max_edge, budget)
    return {"vertices": len(cpos) // 3, "triangles": len(cidx) // 3,
            "positions": digest(np.asarray(cpos, dtype=np.float64).tobytes()),
            "indices": digest(np.asarray(cidx, dtype=np.uint32).tobytes())}


def main():
    tmp = tempfile.mkdtemp()
    out = {"writerTolerance": WRITER_TOL, "exportTolerance": server._EXPORT_TOL,
           "exportAngular": server._EXPORT_ANG_TOL, "fixtures": {}}
    meshes = {}
    for name in FIXTURES:
        sh = read(name)
        pos, idx, _ = tessellate(sh, tolerance=WRITER_TOL, angular_tolerance=server._EXPORT_ANG_TOL)
        pos = np.asarray(pos, dtype=np.float64)
        idx = np.asarray(idx, dtype=np.int64)
        meshes[name] = (pos, idx)
        save_arrays(name, pos, idx)
        rec = {}
        p = os.path.join(tmp, name)
        mesh_writers.write_stl(pos, idx, p + ".stl")
        rec["stl"] = file_digest(p + ".stl")
        mesh_writers.write_stl_ascii(pos, idx, p + ".ascii.stl")
        rec["stlAscii"] = file_digest(p + ".ascii.stl")
        mesh_writers.write_plain_3mf(pos, idx, p + ".3mf")
        rec["3mf"] = model_digest(p + ".3mf")
        inch = pos / 25.4
        mesh_writers.write_plain_3mf(inch, idx, p + ".in.3mf", unit="inch")
        rec["3mfInch"] = model_digest(p + ".in.3mf")
        mesh_writers.write_stl_ascii(inch, idx, p + ".in.ascii.stl")
        rec["stlAsciiInch"] = file_digest(p + ".in.ascii.stl")
        rec["capped3"] = capped(pos, idx, 3.0, server.EXPORT_TRIANGLE_HARD_CAP)
        rec["cappedBudget"] = capped(pos, idx, 0.5, 5000)
        fpos, fidx, _ = tessellate(sh, tolerance=server._EXPORT_TOL,
                                   angular_tolerance=server._EXPORT_ANG_TOL, force_remesh=True)
        rec["exportGrade"] = mesh_stats(fpos, fidx)
        out["fixtures"][name] = rec
        print(name, rec["exportGrade"])

    glb = os.path.join(tmp, "bodies.glb")
    mesh_writers.write_glb([
        {"name": "Box", "positions": meshes["box"][0], "indices": meshes["box"][1], "color": "#ff8800"},
        {"name": "Kugel été \"q\"", "positions": meshes["sphere"][0],
         "indices": meshes["sphere"][1], "color": None},
        {"name": "", "positions": [], "indices": [], "color": "#00ff00"},
        {"name": None, "positions": meshes["box_minus_cylinder"][0],
         "indices": meshes["box_minus_cylinder"][1], "color": "#123456"},
    ], glb)
    out["glb"] = file_digest(glb)
    empty = os.path.join(tmp, "empty.glb")
    mesh_writers.write_glb([], empty)
    out["glbEmpty"] = file_digest(empty)
    out["normColor"] = {str(c): mesh_writers.norm_color(c)
                        for c in ["#ff8800", "FF8800", "#ff880080", "#ggg000", "", None, " #aBcDeF "]}
    out["safeNames"] = {
        label: server._safe_part_filename(label, "body7")
        for label in ["Body 1", "con", "CON.step", "..", "", "a/b\\c:d", "été", "_x_",
                      "lpt9.x", "中" * 150, "a" * 250, "Aux bracket (2)", "trail._"]
    }
    with open(os.path.join(HERE, "oracle.json"), "w", newline="\n", encoding="utf-8") as fh:
        json.dump(out, fh, indent=1, ensure_ascii=False)
        fh.write("\n")


if __name__ == "__main__":
    main()
