"""Differential oracle for fundacad-geom's viewport mesh, generated by the Python sidecar.

Each fixture is a build123d shape written as text BREP (no triangulation), read
back, and meshed through viewport_mesh._compute_payload exactly as a rebuild
does, so the Rust test meshes the very same B-rep. The JSON is a summary of that
payload, not the payload, to keep the fixtures small.

Run from anywhere with the sidecar's interpreter:
    sidecar/.venv/Scripts/python.exe crates/fundacad-geom/tests/mesh_oracle/gen.py
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SIDECAR = os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", "sidecar"))
sys.path.insert(0, SIDECAR)
os.chdir(SIDECAR)

import numpy as np  # noqa: E402
from build123d import (  # noqa: E402
    Axis, Box, Compound, Cone, Cylinder, Pos, Sphere, Torus, fillet, make_face,
    offset, revolve, Polyline, ThreePointArc, Wire,
)
from OCP.BRep import BRep_Builder  # noqa: E402
from OCP.BRepTools import BRepTools  # noqa: E402
from OCP.TopoDS import TopoDS_Shape  # noqa: E402
from OCP.TopTools import TopTools_FormatVersion  # noqa: E402

import OCP  # noqa: E402
import tessellate  # noqa: E402
import viewport_mesh  # noqa: E402
from shape_util import _wrap_topods  # noqa: E402

REQUESTED = 0.1
SAMPLE_DIR = np.array([0.57, 0.31, 0.76])


def shapes():
    b = Box(20, 20, 10)
    yield "box", b
    yield "box_minus_cylinder", b - Cylinder(3, 12)
    yield "filleted_box", fillet(b.edges(), 2)
    yield "sphere", Sphere(10)
    yield "cone", Cone(8, 3, 12)
    yield "torus", Torus(12, 3)
    arc = ThreePointArc((6, 0, 0), (9, 0, 4), (6, 0, 8))
    profile = make_face(Wire([*Polyline((6, 0, 8), (2, 0, 8), (2, 0, 0), (6, 0, 0)).edges(), arc]))
    yield "revolved", revolve(profile, Axis.Z, 360)
    top = b.faces().sort_by(Axis.Z)[-1]
    yield "thin_shell", offset(b, amount=-0.5, openings=[top])
    yield "two_solids", Compound([Box(10, 10, 10), Pos(30, 0, 0) * Sphere(5)])


def mesh_stats(pos, idx):
    P = np.asarray(pos, dtype=np.float64).reshape(-1, 3)
    T = np.asarray(idx, dtype=np.int64).reshape(-1, 3)
    a, b, c = P[T[:, 0]], P[T[:, 1]], P[T[:, 2]]
    cr = np.cross(b - a, c - a)
    area = float(np.linalg.norm(cr, axis=1).sum() / 2)
    volume = float(np.einsum("ij,ij->i", a, np.cross(b, c)).sum() / 6)
    return volume, area


def normal_samples(payload):
    P = np.asarray(payload["positions"], dtype=np.float64).reshape(-1, 3)
    N = np.asarray(payload["normals"], dtype=np.float64).reshape(-1, 3)
    T = np.asarray(payload["indices"], dtype=np.int64).reshape(-1, 3)
    F = np.asarray(payload["faceIds"], dtype=np.int64)
    out = []
    for f in range(payload["faceCount"]):
        verts = np.unique(T[F == f].ravel())
        if len(verts) == 0:
            continue
        d = P[verts] @ SAMPLE_DIR
        for v in {int(verts[int(np.argmin(d))]), int(verts[int(np.argmax(d))])}:
            out.append({"face": f, "point": P[v].tolist(), "normal": N[v].tolist()})
    return out


def main():
    profile = viewport_mesh._viewport_profile(1)
    for name, part in shapes():
        path = os.path.join(HERE, name + ".brep")
        BRepTools.Write_s(part.wrapped, path, False, False, TopTools_FormatVersion.TopTools_FormatVersion_VERSION_3)
        with open(path, "rb") as fh:
            text = fh.read().replace(b"\r\n", b"\n")
        with open(path, "wb") as fh:
            fh.write(text)
        topods = TopoDS_Shape()
        BRepTools.Read_s(topods, path, BRep_Builder())
        sh = _wrap_topods(topods)
        tol = viewport_mesh._effective_tolerance(sh, REQUESTED, profile[0])
        payload = viewport_mesh._compute_payload(name, sh, {}, None, tol, profile)
        fids = payload["faceIds"]
        volume, area = mesh_stats(payload["positions"], payload["indices"])
        summary = {
            "occt": OCP.__version__ if hasattr(OCP, "__version__") else None,
            "codeVersion": tessellate.CODE_VERSION,
            "requested": REQUESTED,
            "effectiveTolerance": tol,
            "angularTolerance": profile[1],
            "keys": list(payload.keys()),
            "faces": len(sh.faces()),
            "faceCount": payload["faceCount"],
            "trisPerFace": np.bincount(np.asarray(fids, dtype=np.int64), minlength=payload["faceCount"]).tolist(),
            "vertices": len(payload["positions"]) // 3,
            "volume": volume,
            "area": area,
            "bbox": payload["bbox"],
            "edgeCount": len(payload["edges"]),
            "edgePoints": [len(e["points"]) for e in payload["edges"]],
            "smooth": [i for i, e in enumerate(payload["edges"]) if e.get("smooth")],
            "hasNormals": payload.get("normals") is not None,
            "normalSamples": normal_samples(payload) if payload.get("normals") else [],
        }
        with open(os.path.join(HERE, name + ".json"), "w", newline="\n") as fh:
            json.dump(summary, fh, indent=1)
            fh.write("\n")
        print(f"{name}: faces {summary['faces']} tris {len(fids)} edges {summary['edgeCount']} "
              f"smooth {len(summary['smooth'])} vol {volume:.4f} area {area:.4f}")


if __name__ == "__main__":
    main()
