"""Differential oracle for fundacad-geom's STEP import, generated by the Python sidecar.

For every sidecar/fixtures/asm_*.step: the product tree `step_assembly.read_assembly`
reads (names, parents, colours, per leaf volume, bbox, face and solid colours)
and the `import` reply `mesh_import.import_geometry` builds from it, with the
blob hash left out since it depends on the kernel version.

Run from anywhere with the sidecar's interpreter:
    sidecar/.venv/Scripts/python.exe crates/fundacad-geom/tests/step/gen.py
"""

import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SIDECAR = os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", "sidecar"))
sys.path.insert(0, SIDECAR)
os.chdir(SIDECAR)

import tempfile  # noqa: E402

os.environ["FUNDACAD_BLOB_DIR"] = tempfile.mkdtemp()

import step_assembly  # noqa: E402
from mesh_import import import_geometry  # noqa: E402
from shape_util import _wrap_topods  # noqa: E402


def hexed(c):
    return c.lower() if c else None


def main():
    out = {}
    for path in sorted(glob.glob(os.path.join(SIDECAR, "fixtures", "asm_*.step"))):
        name = os.path.splitext(os.path.basename(path))[0]
        asm = step_assembly.read_assembly(path)
        leaves = []
        for i, (node, topods) in enumerate(asm.leaves):
            sh = _wrap_topods(topods)
            bb = sh.bounding_box()
            leaves.append({
                "node": node,
                "faces": len(sh.faces()),
                "solids": len(sh.solids()),
                "volume": sh.volume,
                "bbox": [bb.min.X, bb.min.Y, bb.min.Z, bb.max.X, bb.max.Y, bb.max.Z],
                "faceColors": [hexed(c) for c in asm.face_colors[i]] if i in asm.face_colors else None,
                "solidColor": hexed(asm.solid_colors.get(i)),
            })
        reply = import_geometry(path, "step")
        reply.pop("geom")
        out[name] = {
            "isAssembly": asm.is_assembly,
            "roots": len(asm.roots),
            "nodes": [{"name": n.name, "parent": n.parent, "color": hexed(n.color)} for n in asm.nodes],
            "leaves": leaves,
            "reply": reply,
        }
        print(name, len(asm.nodes), "nodes", len(asm.leaves), "leaves")
    with open(os.path.join(HERE, "oracle.json"), "w", newline="\n", encoding="utf-8") as fh:
        json.dump(out, fh, indent=1, ensure_ascii=False)
        fh.write("\n")


if __name__ == "__main__":
    main()
