"""Differential oracle for fundacad-geom's canonical recognition, generated by the Python sidecar.

Each fixture is a tests/mesh_oracle BREP turned wholly into NURBS
(BRepBuilderAPI_NurbsConvert), written here as text BREP so both engines
start from the same splines, then run through `mesh_import._canonicalize`.

Run from anywhere with the sidecar's interpreter:
    sidecar/.venv/Scripts/python.exe crates/fundacad-geom/tests/canonical/gen.py
"""

import json
import os
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ORACLE = os.path.normpath(os.path.join(HERE, "..", "mesh_oracle"))
SIDECAR = os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", "sidecar"))
sys.path.insert(0, SIDECAR)
os.chdir(SIDECAR)

from OCP.BRep import BRep_Builder  # noqa: E402
from OCP.BRepAdaptor import BRepAdaptor_Surface  # noqa: E402
from OCP.BRepBuilderAPI import BRepBuilderAPI_NurbsConvert  # noqa: E402
from OCP.BRepCheck import BRepCheck_Analyzer  # noqa: E402
from OCP.BRepTools import BRepTools  # noqa: E402
from OCP.TopoDS import TopoDS_Shape  # noqa: E402
from OCP.TopTools import TopTools_FormatVersion  # noqa: E402

from mesh_import import _canonicalize  # noqa: E402
from shape_util import _wrap_topods  # noqa: E402

FIXTURES = ["box_minus_cylinder", "cone", "sphere", "filleted_box"]


def summary(sh):
    kinds = Counter(str(BRepAdaptor_Surface(f.wrapped).GetType()).split(".")[-1] for f in sh.faces())
    return {
        "faces": len(sh.faces()),
        "solids": len(sh.solids()),
        "volume": sh.volume,
        "valid": bool(BRepCheck_Analyzer(sh.wrapped).IsValid()),
        "surfaces": dict(sorted(kinds.items())),
    }


def main():
    out = {}
    for name in FIXTURES:
        topods = TopoDS_Shape()
        BRepTools.Read_s(topods, os.path.join(ORACLE, name + ".brep"), BRep_Builder())
        nurbs = BRepBuilderAPI_NurbsConvert(topods, True).Shape()
        path = os.path.join(HERE, name + ".nurbs.brep")
        BRepTools.Write_s(nurbs, path, False, False, TopTools_FormatVersion.TopTools_FormatVersion_VERSION_3)
        with open(path, "rb") as fh:
            text = fh.read().replace(b"\r\n", b"\n")
        with open(path, "wb") as fh:
            fh.write(text)
        back = TopoDS_Shape()
        BRepTools.Read_s(back, path, BRep_Builder())
        shape = _wrap_topods(back)
        result = _canonicalize(shape)
        out[name] = {"input": summary(shape), "changed": result is not shape, "output": summary(result)}
        print(name, out[name]["changed"], out[name]["output"])
    with open(os.path.join(HERE, "oracle.json"), "w", newline="\n") as fh:
        json.dump(out, fh, indent=1)
        fh.write("\n")


if __name__ == "__main__":
    main()
