"""Differential oracle for the `projectGeometry` op and a rebuild's projection
refresh, generated by the Python sidecar.

`op` cases record builder.project_geometry for a request; `rebuild` cases
record what server._rebuild_job answered for a document with projected
entities, reduced to the keys the refresh decides. The documents come from
the sidecar's own test_project_op.py, test_silhouette.py and test_refresh.py,
with the seeded caches those tests derive written out verbatim.

Run from anywhere with the sidecar's interpreter:
    sidecar/.venv/Scripts/python.exe crates/fundacad-geom/tests/projection/gen.py
"""

import copy
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SIDECAR = os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", "sidecar"))
sys.path.insert(0, SIDECAR)
sys.path.insert(0, os.path.join(SIDECAR, "tests"))
os.environ.setdefault("FUNDACAD_DISK_CACHE", "0")
os.chdir(SIDECAR)

import builder  # noqa: E402
import server  # noqa: E402
import test_project_op as tpo  # noqa: E402
import test_refresh as trf  # noqa: E402
import test_silhouette as tsil  # noqa: E402
from builder import project_geometry  # noqa: E402

CASES = []


def op(name, doc, plane, sources):
    res = project_geometry(doc, plane, sources)
    CASES.append({"name": name, "kind": "op",
                  "request": {"op": "projectGeometry", "document": doc, "plane": plane, "sources": sources},
                  "result": res})
    return res


def rebuild(name, doc):
    builder.reset_cache()
    res = server._rebuild_job(doc, 0.1)
    keep = {k: res[k] for k in ("projectionUpdates", "featureError", "error") if k in res}
    keep["bodyCount"] = len(res.get("bodies") or [])
    CASES.append({"name": name, "kind": "rebuild", "document": doc, "result": keep})
    return res.get("projectionUpdates") or []


def near(point):
    return {"kind": "edge", "by": "nearest", "point": point}


def main():
    op("box_top_boundary", tpo.BOX, "XY", [{"kind": "faceBoundary", "body": "body1",
        "sel": {"kind": "face", "by": "nearest", "point": [0, 0, 10]}}])
    op("cylinder_rim", tpo.CYL, "XY", [{"kind": "edge", "body": "body1", "sel": near([0, 0, 10.1])}])
    op("cylinder_rim_tilted", tpo.CYL, tpo.TILTED, [{"kind": "edge", "body": "body1", "sel": near([0, 0, 10.1])}])
    op("vertical_edge", tpo.BOX, "XY", [{"kind": "edge", "body": "body1", "sel": near([10, 10, 5])}])
    cross = {"parameters": {}, "features": [
        {"id": "s0", "type": "sketch", "plane": "XZ", "entities": [
            {"id": "l1", "type": "line", "x1": 1, "y1": 2, "x2": 5, "y2": 2},
            {"id": "c1", "type": "circle", "radius": 2, "x": 3, "y": 4}]}]}
    op("sketch_cross_plane", cross, "XY", [
        {"kind": "sketchCurve", "sketch": "s0", "entity": "l1"},
        {"kind": "sketchCurve", "sketch": "s0", "entity": "c1"}])
    same = {"parameters": {"rad": 4}, "features": [
        {"id": "s0", "type": "sketch", "plane": "XY", "entities": [
            {"id": "c1", "type": "circle", "radius": "rad", "x": 2, "y": 3},
            {"id": "a1", "type": "arc", "x1": 0, "y1": 0, "x2": 10, "y2": 0, "mx": 5, "my": 5},
            {"id": "r1", "type": "rectangle", "width": 8, "height": 6, "x": 0, "y": 0},
            {"id": "pt", "type": "point", "x": 1, "y": 1}]}]}
    op("sketch_same_plane", same, "XY", [
        {"kind": "sketchCurve", "sketch": "s0", "entity": "c1"},
        {"kind": "sketchCurve", "sketch": "s0", "entity": "a1"},
        {"kind": "sketchCurve", "sketch": "s0", "entity": "r1"},
        {"kind": "sketchCurve", "sketch": "s0", "entity": "pt"}])
    op("error_entries", tpo.BOX, "XY", [
        {"kind": "edge", "body": "nope", "sel": near([0, 0, 0])},
        {"kind": "sketchCurve", "sketch": "nope", "entity": "x"},
        {"kind": "sketchCurve", "sketch": "s1", "entity": "nope"},
        {"kind": "edge", "body": "body1", "sel": {"kind": "edge", "by": "match",
            "fp": {"mid": [999, 999, 999], "dir": [1, 0, 0], "length": 1, "curve": "line"}}},
        {"kind": "silhouette", "body": "nope"},
        {"kind": "mystery"}])
    cyl = {"parameters": {}, "features": tsil._cyl_features()}
    op("cylinder_silhouette", cyl, tsil.SIDE, [{"kind": "silhouette", "body": "body1"}])
    turned = {"parameters": {}, "features": [
        {"id": "c", "type": "cylinder", "radius": 10, "height": 30},
        {"id": "m", "type": "move", "rz": 30}]}
    op("turned_cylinder_silhouette", turned, tsil.SIDE, [{"kind": "silhouette", "body": "body1"}])
    op("sphere_silhouette", {"parameters": {}, "features": [{"id": "s", "type": "sphere", "radius": 8}]},
       "XY", [{"kind": "silhouette", "body": "body1"}])

    # the refresh, as test_silhouette.py drives it
    garbage = {k: dict(tsil.WRONG) for k in ("p0", "p1", "p2", "p3")}
    upd = rebuild("silhouette_wrong_cache", tsil._sil_doc(tsil._cyl_features(), garbage))
    seeded = {u["entity"]: u["curve"] for u in upd}
    rebuild("silhouette_steady", tsil._sil_doc(tsil._cyl_features(), seeded))
    rebuild("silhouette_resized", tsil._sil_doc(tsil._cyl_features(r=15), seeded))
    sphere_features = [
        {"id": "f1", "type": "sketch", "plane": "XZ", "entities": [
            {"id": "a1", "type": "arc", "x1": 0, "y1": -8, "x2": 0, "y2": 8, "mx": 8, "my": 0},
            {"id": "l1", "type": "line", "x1": 0, "y1": 8, "x2": 0, "y2": -8}]},
        {"id": "f2", "type": "revolve", "sketch": "f1", "axis": "Z", "angle": 360, "operation": "new"},
    ]
    rebuild("silhouette_shrunk_to_sphere", tsil._sil_doc(sphere_features, seeded))
    missing = tsil._sil_doc([f for f in tsil._cyl_features() if f["id"] != "f2"], seeded)
    rebuild("silhouette_missing_body", missing)
    quiet = copy.deepcopy(missing)
    for e in quiet["features"][1]["entities"]:
        e["stale"] = True
    rebuild("silhouette_missing_body_quiet", quiet)

    # the refresh, as test_refresh.py drives it
    src, true_curve = trf._edge_source()
    rebuild("edge_wrong_cache", trf._doc(trf.WRONG, src))
    rebuild("edge_steady", trf._doc(true_curve, src))
    gone = trf._doc(true_curve, src)
    gone["features"] = [f for f in gone["features"] if f["id"] != "f2"]
    rebuild("edge_body_gone", gone)
    rebuild("edge_stale_clears", trf._doc(true_curve, src, stale=True))
    rebuild("edge_upstream_wider", trf._doc(true_curve, src, w=60))

    def sk_doc(rect_x, ents):
        return {"parameters": {}, "features": [
            {"id": "f1", "type": "sketch", "plane": "XY",
             "entities": [{"id": "r1", "type": "rectangle", "width": 20, "height": 10, "x": rect_x, "y": 0}]},
            {"id": "f3", "type": "sketch", "plane": trf.TOP, "entities": ents},
        ]}

    no_index = [{"id": f"e{i}", "type": "projected",
                 "source": {"kind": "sketchCurve", "sketch": "f1", "entity": "r1", "group": "e1"},
                 "curve": dict(trf.WRONG)} for i in range(1, 5)]
    rebuild("sketch_curve_without_index", sk_doc(0, no_index))

    def indexed(ids, cached):
        return [{"id": eid, "type": "projected",
                 "source": {"kind": "sketchCurve", "sketch": "f1", "entity": "r1", "group": "e1", "index": i},
                 "curve": cached[eid]} for i, eid in ids]

    all_ids = [(i - 1, f"e{i}") for i in range(1, 5)]
    upd = rebuild("sketch_curve_indexed", sk_doc(0, indexed(all_ids, {k: dict(trf.WRONG) for k in ("e1", "e2", "e3", "e4")})))
    seeded = {u["entity"]: u["curve"] for u in upd}
    rebuild("sketch_curve_index_after_delete", sk_doc(5, indexed([(0, "e1"), (2, "e3"), (3, "e4")], seeded)))

    chain = trf._doc(true_curve, src, tail=[
        {"id": "f4", "type": "sketch", "plane": trf.TOP, "entities": [
            {"id": "q1", "type": "projected",
             "source": {"kind": "sketchCurve", "sketch": "f3", "entity": "p1"},
             "curve": dict(trf.WRONG)}]}])
    op("chain_projection", chain, trf.TOP, [{"kind": "sketchCurve", "sketch": "f3", "entity": "p1"}])
    rebuild("chain_projection", chain)

    with open(os.path.join(HERE, "oracle.json"), "w", newline="\n") as fh:
        json.dump(CASES, fh, indent=1)
        fh.write("\n")
    for c in CASES:
        print(c["kind"], c["name"], json.dumps(c["result"])[:150])


if __name__ == "__main__":
    main()
