"""Differential oracle for the `inspect` and `interference` ops, generated by the Python sidecar.

Each case is a request and what server._inspect_job or server._interference_job
answered for it, so the Rust test runs the same request through the same op.

Run from anywhere with the sidecar's interpreter:
    sidecar/.venv/Scripts/python.exe crates/fundacad-geom/tests/inspect/gen.py
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SIDECAR = os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", "sidecar"))
sys.path.insert(0, SIDECAR)
os.chdir(SIDECAR)

import server  # noqa: E402


def rect(idx, w, h, depth, x=0, y=0, op="new"):
    s = f"s{idx}"
    return [
        {"id": s, "type": "sketch", "plane": "XY",
         "entities": [{"id": f"r{idx}", "type": "rectangle", "width": w, "height": h, "x": x, "y": y}]},
        {"id": f"e{idx}", "type": "extrude", "sketch": s, "distance": depth, "operation": op},
    ]


def circle(idx, r, depth, op="new"):
    s = f"c{idx}"
    return [
        {"id": s, "type": "sketch", "plane": "XY",
         "entities": [{"id": f"k{idx}", "type": "circle", "radius": r, "x": 0, "y": 0}]},
        {"id": f"x{idx}", "type": "extrude", "sketch": s, "distance": depth, "operation": op},
    ]


def doc(*lists):
    return {"parameters": {}, "features": [f for fl in lists for f in fl]}


def inspect_cases():
    yield "box", doc([{"id": "b", "type": "box", "length": 20, "width": 10, "height": 4}]), {}
    yield "cylinder", doc([{"id": "c", "type": "cylinder", "radius": 10, "height": 20}]), {}
    yield "washer", doc(circle(1, 10, 4), circle(2, 5, 4, "cut")), {}
    yield "sphere", doc([{"id": "s", "type": "sphere", "radius": 6}]), {}
    yield "cone", doc([{"id": "k", "type": "cone", "bottomRadius": 8, "topRadius": 3, "height": 12}]), {}
    yield "two_bodies_filtered", doc(rect(1, 10, 10, 10), rect(2, 2, 2, 2, 40, 0)), {"bodies": ["Body2"]}
    yield "failing_feature", doc([
        {"id": "b", "type": "box", "length": 10, "width": 10, "height": 10},
        {"id": "x", "type": "shell", "thickness": 0},
    ]), {}
    yield "no_detail", doc([{"id": "b", "type": "box", "length": 20, "width": 10, "height": 4}]), {"detail": False}
    yield "capped", doc([{"id": "b", "type": "box", "length": 20, "width": 10, "height": 4}]), {"maxFaces": 2, "maxEdges": 3}
    yield "l_shape", doc(rect(1, 30, 10, 10, 0, 0), rect(2, 10, 20, 10, -10, 15, "join")), {}


def interference_cases():
    yield "overlap", doc(rect(1, 20, 20, 20, 0, 0), rect(2, 20, 20, 20, 10, 10)), None
    yield "touching", doc(rect(1, 20, 20, 20, 0, 0), rect(2, 20, 20, 20, 20, 0)), None
    gap = doc(rect(1, 20, 20, 20, 0, 0), rect(2, 20, 20, 20, 20.1, 0))
    yield "gap_generous", gap, 0.2
    yield "gap_tight", gap, 0.05
    yield "gap_off", gap, None
    yield "four_stacked", doc(*[rect(i, 20, 20, 20, i * 2, 0) for i in range(4)]), 0.5
    yield "nothing_built", doc([{"id": "b", "type": "box", "length": 0, "width": 1, "height": 1}]), None


def main():
    cases = []
    for name, document, extra in inspect_cases():
        req = {"op": "inspect", "document": document, **extra}
        res = server._inspect_job(document, bool(req.get("detail", True)), req.get("bodies"),
                                  req.get("maxFaces"), req.get("maxEdges"))
        cases.append({"name": name, "request": req, "result": res})
        print(f"inspect {name}: {len(res['bodies'])} bodies, {len(res['errors'])} errors")
    for name, document, clearance in interference_cases():
        req = {"op": "interference", "document": document}
        if clearance is not None:
            req["clearance"] = clearance
        res = server._interference_job(document, clearance)
        for p in res.get("pairs", []):
            p["triangles"] = len(p.pop("indices", [])) // 3
            p.pop("positions", None)
        cases.append({"name": name, "request": req, "result": res})
        print(f"interference {name}: {json.dumps(res)[:160]}")
    with open(os.path.join(HERE, "oracle.json"), "w", newline="\n") as fh:
        json.dump(cases, fh, indent=1)
        fh.write("\n")


if __name__ == "__main__":
    main()
