"""Differential oracle for fundacad-geom::topo and ::faces, generated by the Python sidecar.

Each fixture is a build123d shape written as text BREP, read back, and asked
the questions topo_adj.FaceAdjacency, topo_adj.face_wraps and
face_bands.face_bands answer, so the Rust test asks them of the same B-rep.

Run from anywhere with the sidecar's interpreter:
    sidecar/.venv/Scripts/python.exe crates/fundacad-geom/tests/faces/gen.py
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SIDECAR = os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", "sidecar"))
sys.path.insert(0, SIDECAR)
sys.path.insert(0, os.path.join(SIDECAR, "tests"))
os.chdir(SIDECAR)

from build123d import Box, Compound, Cylinder, Pos, Rot, Sphere, fillet  # noqa: E402
from OCP.BRep import BRep_Builder  # noqa: E402
from OCP.BRepTools import BRepTools  # noqa: E402
from OCP.TopAbs import TopAbs_EDGE  # noqa: E402
from OCP.TopExp import TopExp  # noqa: E402
from OCP.TopoDS import TopoDS_Shape  # noqa: E402
from OCP.TopTools import TopTools_FormatVersion, TopTools_IndexedMapOfShape  # noqa: E402

import builder  # noqa: E402
import face_bands  # noqa: E402
from shape_util import _wrap_topods  # noqa: E402
from topo_adj import FaceAdjacency, face_wraps  # noqa: E402
import test_face_bands as tfb  # noqa: E402


def write_brep(shape, path):
    BRepTools.Write_s(shape.wrapped, path, False, False,
                      TopTools_FormatVersion.TopTools_FormatVersion_VERSION_3)
    with open(path, "rb") as fh:
        text = fh.read().replace(b"\r\n", b"\n")
    with open(path, "wb") as fh:
        fh.write(text)
    topods = TopoDS_Shape()
    BRepTools.Read_s(topods, path, BRep_Builder())
    return _wrap_topods(topods)


def shapes():
    yield "box", Box(20, 20, 10)
    yield "cylinder", Cylinder(5, 10)
    yield "sphere", Sphere(5)
    yield "tube", Cylinder(5, 10) - Cylinder(3, 10)
    yield "grooved_ring", Cylinder(5, 20) - (Cylinder(6, 2) - Cylinder(4.6, 2))
    yield "stepped_shaft", builder._serial_bool(Cylinder(5, 10), Pos(0, 0, 10) * Cylinder(3, 10), "fuse")
    yield "filleted_box", fillet(Box(20, 20, 10).edges(), 2)
    yield "apart", Compound([Box(10, 10, 10), Pos(50, 0, 0) * Box(10, 10, 10)])
    yield "touching", Compound([Box(10, 10, 10), Pos(10, 0, 0) * Box(10, 10, 10)])
    yield "fused", Box(10, 10, 10) + Pos(10, 0, 0) * Box(10, 10, 10)
    yield "split_wall", tfb._split_wall()
    yield "split_wall_moved", Pos(137.5, -42.25, 9.75) * Rot(23, 41, 67) * tfb._split_wall()
    yield "grooved_shaft", tfb._grooved_shaft()
    plate = Box(40, 10, 2)
    for x in (-12, 12):
        plate = builder._serial_bool(plate, Pos(x, 0, 2.5) * Box(6, 6, 3), "fuse")
    yield "two_pads", plate
    yield "hairline", Compound([Box(10, 10, 4), Pos(10 + 5e-4, 0, 0) * Box(10, 10, 4)])
    yield "five_microns", Compound([Box(10, 10, 4), Pos(10 + 5e-3, 0, 0) * Box(10, 10, 4)])
    yield "drawn_gap", Compound([Box(10, 10, 4), Pos(11, 0, 0) * Box(10, 10, 4)])
    yield "strips_same", Compound([tfb._cyl_strip(0, 5, True), tfb._cyl_strip(5, 10, True)])
    yield "strips_flipped", Compound([tfb._cyl_strip(0, 5, True), tfb._cyl_strip(5, 10, False)])
    yield "torus_same", Compound([tfb._torus_arc(0.0, 1.5, True), tfb._torus_arc(1.5, 3.0, True)])
    yield "torus_flipped", Compound([tfb._torus_arc(0.0, 1.5, True), tfb._torus_arc(1.5, 3.0, False)])
    for up in (True, False):
        tag = "up" if up else "down"
        yield f"strips_sides_{tag}", Compound([
            tfb._cyl_strip(0, 5, True, reversed_face=False),
            tfb._cyl_strip(5, 10, up, reversed_face=True)])
        yield f"strips_sides_other_{tag}", Compound([
            tfb._cyl_strip(0, 5, True, reversed_face=True),
            tfb._cyl_strip(5, 10, up, reversed_face=False)])
        yield f"torus_sides_{tag}", Compound([
            tfb._torus_arc(0.0, 1.5, True),
            tfb._torus_arc(1.5, 3.0, up, reversed_face=True)])


def main():
    names = []
    for name, part in shapes():
        sh = write_brep(part, os.path.join(HERE, name + ".brep"))
        adj = FaceAdjacency(sh)
        emap = TopTools_IndexedMapOfShape()
        TopExp.MapShapes_s(sh.wrapped, TopAbs_EDGE, emap)
        summary = {
            "extent": adj.extent,
            "neighbors": [sorted(adj.neighbors(i)) for i in adj.indices()],
            "walkCounts": [sum(1 for _ in adj.walk(i)) for i in adj.indices()],
            "edgeFaces": [adj.faces_of_edge(emap.FindKey(i)) for i in range(1, emap.Extent() + 1)],
            "components": sorted(sorted(c) for c in adj.components()),
            "wraps": [face_wraps(adj.face(i)) for i in adj.indices()],
            "faces": len(sh.faces()),
            "bands": face_bands.face_bands(sh),
            "gapTolerance": face_bands.gap_tolerance(sh),
        }
        with open(os.path.join(HERE, name + ".json"), "w", newline="\n") as fh:
            json.dump(summary, fh, indent=1)
            fh.write("\n")
        names.append(name)
        print(f"{name}: faces {summary['faces']} bands {summary['bands']}")
    with open(os.path.join(HERE, "fixtures.json"), "w", newline="\n") as fh:
        json.dump(names, fh, indent=1)
        fh.write("\n")


if __name__ == "__main__":
    main()
