"""Differential oracle for fundacad-geom's mesh import, generated by the Python sidecar.

The input files are written from tests/export/*.mesh by the Python writers,
which the Rust writers match byte for byte (tests/export_writers.rs), so the
Rust test writes the very same files and nothing model shaped is committed.
Each import reply is kept without its blob hash, with the volume and bounding
box of the stored shape.

Run from anywhere with the sidecar's interpreter:
    sidecar/.venv/Scripts/python.exe crates/fundacad-geom/tests/mesh_import/gen.py
"""

import json
import os
import struct
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
MESHES = os.path.normpath(os.path.join(HERE, "..", "export"))
SIDECAR = os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", "sidecar"))
sys.path.insert(0, SIDECAR)
os.chdir(SIDECAR)
os.environ["FUNDACAD_BLOB_DIR"] = tempfile.mkdtemp()

import numpy as np  # noqa: E402

import blobstore  # noqa: E402
import geomstore  # noqa: E402
import mesh_writers  # noqa: E402
from mesh_import import import_geometry  # noqa: E402
from shape_util import _wrap_topods  # noqa: E402

FIXTURES = ["box", "box_minus_cylinder", "two_solids"]
FORMATS = ["stl", "ascii.stl", "3mf", "obj", "glb"]


def arrays(name):
    with open(os.path.join(MESHES, name + ".mesh"), "rb") as fh:
        nv, nt = struct.unpack("<II", fh.read(8))
        pos = np.frombuffer(fh.read(nv * 24), dtype="<f8")
        idx = np.frombuffer(fh.read(nt * 12), dtype="<u4")
    return pos, idx


def write(pos, idx, path, fmt):
    if fmt == "stl":
        mesh_writers.write_stl(pos, idx, path)
    elif fmt == "ascii.stl":
        mesh_writers.write_stl_ascii(pos, idx, path)
    elif fmt == "3mf":
        mesh_writers.write_plain_3mf(pos, idx, path)
    elif fmt == "glb":
        mesh_writers.write_glb([{"name": "Part", "positions": pos, "indices": idx, "color": "#3366cc"}], path)
    else:
        with open(path, "w", newline="\n") as fh:
            for i in range(0, len(pos), 3):
                fh.write(f"v {float(pos[i])!r} {float(pos[i + 1])!r} {float(pos[i + 2])!r}\n")
            for i in range(0, len(idx), 3):
                fh.write(f"f {idx[i] + 1} {idx[i + 1] + 1} {idx[i + 2] + 1}\n")


def main():
    tmp = tempfile.mkdtemp()
    out = {}
    for name in FIXTURES:
        pos, idx = arrays(name)
        for fmt in FORMATS:
            path = os.path.join(tmp, f"{name}.{fmt}")
            write(pos, idx, path, fmt)
            key = f"{name}.{fmt}"
            try:
                reply = import_geometry(path, fmt.split(".")[-1])
            except Exception as ex:  # noqa: BLE001
                out[key] = {"error": str(ex)}
                print(key, "error", ex)
                continue
            data = blobstore.default_store().get_bytes(reply.pop("geom"))
            sh = _wrap_topods(geomstore.deserialize_shape(data))
            bb = sh.bounding_box()
            out[key] = {
                "reply": reply,
                "volume": sh.volume,
                "solids": len(sh.solids()),
                "bbox": [bb.min.X, bb.min.Y, bb.min.Z, bb.max.X, bb.max.Y, bb.max.Z],
            }
            print(key, reply, round(sh.volume, 3))
    with open(os.path.join(HERE, "oracle.json"), "w", newline="\n", encoding="utf-8") as fh:
        json.dump(out, fh, indent=1)
        fh.write("\n")


if __name__ == "__main__":
    main()
